hi ColorColumn guibg=#2d2d2d

#if os == "Darwin"
#  set guifont=Monaco:h9
#else
#  set guifont=Terminus\ Medium\ 8
#endif

set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
