hi ColorColumn guibg=#2d2d2d

if os == "Darwin"
  set guifont=Monaco:h9
else
  set guifont=Ubuntu\ Mono:10
endif

set guifont=Ubuntu\ Mono\ 10
set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
