" set rtp+=~/.vim/bundle/vundle/
" call vundle#rc()

"Bundle 'scrooloose/nerdtree'
"Bundle 'ervandew/supertab'
"Bundle 'tpope/vim-rails'

call pathogen#infect()

let g:solarized_termcolors=256
let g:solarized_hitrail=1
colorscheme molokai

set t_Co=256

set autoindent
set smartindent

" Tab stop settings
set tabstop=2 softtabstop=2 shiftwidth=2 expandtab
" Might not need softtabstop=2 here
command TabDefault set tabstop=2 softtabstop=2 shiftwidth=2 expandtab
command TabKernel  set tabstop=8 softtabstop=8 shiftwidth=8 noexpandtab

" Text width settings
set textwidth=81
let &colorcolumn="".join(range(81,999),",")
command Tw80  set textwidth=81  | let &colorcolumn="".join(range(81,999),",")
command Tw100 set textwidth=101 | let &colorcolumn="81,".join(range(101,999),",")
command Tw120 set textwidth=121 | let &colorcolumn="81,".join(range(121,999),",")

set showmatch
set guioptions-=T

let os = substitute(system('uname'), "\n", "", "")

set vb t_vb=
syntax on
" Sets column highlight color, needs to be after 'syntax on' line
hi ColorColumn ctermbg=234

set ruler
set incsearch
set number

filetype plugin indent on

" Shortcuts

map <C-f> :NERDTreeToggle<CR>
map <C-j> :FufCoverageFile<CR>
map <C-i> :FufRenewCache<CR>
" Erroring for some reason
"call togglebg#map("<F5>")

" TabBar Customization

let g:Tb_SplitBelow=1
let g:Tb_MaxSize=0
let g:Tb_MoreThanOne=0
let g:Tb_ModSelTarget=1
