#x setup
xrdb ~/.Xresources
xset +fp /usr/share/fonts/local
xset fp rehash
sh ~/.fehbg &

#application startup
~/.dropbox-dist/dropboxd &
xflux -z 95928 &

#dualhead setup
if cat /etc/hostname | grep -q nix
then
  xrandr --output DVI-0 --auto --right-of HDMI-0
fi

#wm main loop
exec i3
